FROM pytorch/pytorch:1.12.0-cuda11.3-cudnn8-runtime

RUN pip3 install pandas jupyterlab runnb tira==0.0.28

# Install custom requirements HERE
COPY requirements_svm.txt /workspace/requirements.txt
RUN pip3 install -r requirements.txt

ENV PYTHONPATH=/workspace

COPY components /workspace/components/
COPY core_data /workspace/core_data/
COPY models/svm /workspace/models/svm/

# Copy execution notebook
COPY predict_svm_notebook.ipynb /workspace/

RUN jupyter trust /workspace/predict_svm_notebook.ipynb
