FROM anibali/pytorch:1.10.2-nocuda-ubuntu20.04

COPY requirements_svm.txt /app/requirements.txt
RUN pip install -r requirements.txt
USER root
COPY components/ /app/components
COPY core_data/ /app/data
COPY models/svm/ /app/models
COPY predict_svm.py /app/predict.py
