FROM pytorch/pytorch:1.12.0-cuda11.3-cudnn8-runtime

RUN pip3 install pandas jupyterlab runnb tira==0.0.65

# Install custom requirements HERE
COPY requirements.txt /workspace/requirements.txt
RUN pip3 install -r requirements.txt

ENV PYTHONPATH=/workspace

COPY components /workspace/components/
COPY models /workspace/models/

# pre-load autotokenizer
RUN mkdir /workspace/tokenizer
COPY download_bert_tokenizer.py /workspace/
RUN python3 /workspace/download_bert_tokenizer.py

# Copy execution notebook
COPY predict_bert_notebook.ipynb /workspace/

RUN jupyter trust /workspace/predict_bert_notebook.ipynb
