FROM pytorch/pytorch:1.12.0-cuda11.3-cudnn8-runtime

# Install custom requirements HERE
COPY requirements.txt /workspace/requirements.txt
RUN pip3 install -r requirements.txt

ENV PYTHONPATH=/workspace

COPY components/ /workspace/components
COPY training.py /workspace/training.py
